apiVersion: v1
kind: Service
metadata:
  name: bike-sharing-api
spec:
  type: NodePort
  selector:
    app: bike-sharing-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
